### ISSUE TITLE
Compatibility Error on Install

### ISSUE THREAD

**Issue by TheCrimsonKing92** [asledgehammer/ZedScript-VSCode#1]
I wasn't initially able to install the extension, until I restarted multiple times to update Visual Studio Code to 1.76.2. Prior to that, install provoked an error ("Can't install 'asledgehammer.zedscript-vscode' extension because it is not compatible with the current version of Visual Studio Code (version <version number>).").

The attempted versions which didn't allow install were 1.74.3 and 1.75.1.

**Comment by TheCrimsonKing92** [comment]
![image](https://user-images.githubusercontent.com/12803415/227376673-ba9c5c00-1c91-41fb-92ed-d66f64bf2236.png)

**Comment by JabDoesThings** [comment]
Check and see if your issue is resolved. (run `npm i` again)
